<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>RBI-Malaysia</RootNamespace>
    <AssemblyName>$(AssemblyName.Replace(' ', '_'))</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\ValidationBase.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Components\Pages\Amineqeqweqweqwe.razor" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Stimulsoft.Base">
      <HintPath>..\StudentRecorder\Lib\Stimulsoft.Base.dll</HintPath>
    </Reference>
    <Reference Include="Stimulsoft.Controls">
      <HintPath>..\StudentRecorder\Lib\Stimulsoft.Controls.dll</HintPath>
    </Reference>
    <Reference Include="Stimulsoft.Controls.Win">
      <HintPath>..\StudentRecorder\Lib\Stimulsoft.Controls.Win.dll</HintPath>
    </Reference>
    <Reference Include="Stimulsoft.Database">
      <HintPath>..\StudentRecorder\Lib\Stimulsoft.Database.dll</HintPath>
    </Reference>
    <Reference Include="Stimulsoft.Design">
      <HintPath>..\StudentRecorder\Lib\Stimulsoft.Design.dll</HintPath>
    </Reference>
    <Reference Include="Stimulsoft.Editor">
      <HintPath>..\StudentRecorder\Lib\Stimulsoft.Editor.dll</HintPath>
    </Reference>
    <Reference Include="Stimulsoft.Report">
      <HintPath>..\StudentRecorder\Lib\Stimulsoft.Report.dll</HintPath>
    </Reference>
    <Reference Include="Stimulsoft.Report.Check">
      <HintPath>..\StudentRecorder\Lib\Stimulsoft.Report.Check.dll</HintPath>
    </Reference>
    <Reference Include="Stimulsoft.Report.Design">
      <HintPath>..\StudentRecorder\Lib\Stimulsoft.Report.Design.dll</HintPath>
    </Reference>
    <Reference Include="Stimulsoft.Report.Helper">
      <HintPath>..\StudentRecorder\Lib\Stimulsoft.Report.Helper.dll</HintPath>
    </Reference>
    <Reference Include="Stimulsoft.Report.Web">
      <HintPath>..\StudentRecorder\Lib\Stimulsoft.Report.Web.dll</HintPath>
    </Reference>
    <Reference Include="Stimulsoft.Report.Win">
      <HintPath>..\StudentRecorder\Lib\Stimulsoft.Report.Win.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
